site_name: Kvrmnks's Blog
nav:
  - Home: index.md
  - About: about.md
  - Blog: blog.md

markdown_extensions:
    - mdx_math:
       enable_dollar_delimiter: True

extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML